[package]
name = "plugin_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tauri = { version = "2.0.0-beta" }
reqwest = "0.12.4"

[build-dependencies]
tonic-build = "0.11"
